core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns= [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('pricing/', views.pricing, name='pricing')
]

link/urls.py
from django.urls import path


from . import views

app_name = 'links'

urlpatterns = [
    path('', views.links, name='links'),
    path('<int:pk>/edit/', views.edit_link, name='edit_link'),
    path('<int:pk>/delete/', views.delete_link, name='delete_link'),
    path('create-link/', views.create_link, name='create_link'),
    path('categories/', views.categories, name='categories'),
    path('categories/<int:pk>/edit/', views.edit_category, name='edit_category'),
    path('categories/<int:pk>/delete/', views.delete_category, name='delete_category'),
    path('categories/create-category/', views.create_category, name='create_category'),
]

lynko/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include('core.urls')),
    path('', include('accounts.urls')),
    path('links/', include('link.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
     path("stripe/", include("djstripe.urls", namespace="djstripe")),
]

link/models.py
from django.db import models

# Create your models here.
from accounts.models import User

class Category(models.Model):
    name = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, related_name='categories', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=('name',)

    def __str__ (self):
        return self.name

class Link(models.Model):
    category = models.ForeignKey(Category, related_name='links', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    url = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, related_name='links', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

link/forms.py
from django import forms

from .models import Category, Link

class CategoryForm(forms.ModelForm):
    class Meta:
        model= Category
        fields = ('name',)



class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ('category', 'name', 'description', 'url')

link/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

# Create your views here.
from .forms import CategoryForm, LinkForm
from .models import Category, Link

@login_required
def links(request):
    category = request.GET.get('category', '')
    links = Link.objects.filter(created_by=request.user)

    if category:
        link = links.filter(category_id=category)

    return render(request, 'link/links.html',{
        'link': links,
        'category': category,
    })


@login_required
def categories(request):
    categories = Category.objects.filter(created_by=request.user)

    return render(request, 'link/categories.html',{
        'categories': categories,
      })


@login_required
def create_link(request):
    if request.method == 'POST':
        form = LinkForm(request.POST)

        if form.is_valid():
            link = form.save(commit=False)
            link.created_by=request.user
            link.save()

            return redirect('/dashboard/')
    else:
        form = LinkForm()
        form.fields['category'].queryset = Category.objects.filter(created_by=request.user)

    return render(request, 'link/create_link.html', {
        'form': form,
        'title': 'Create link'
    })


@login_required
def edit_link(request, pk):
    link = get_object_or_404(Link, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form = LinkForm(request.POST, instance=link)

        if form.is_valid():
            form.save()

            return redirect('/links/')
    else:
        form = LinkForm(instance=link)
        form.fields['category'].queryset = Category.objects.filter(created_by=request.user)

    return render(request, 'link/create_link.html', {
        'form': form,
        'title': 'Edit link'
    })


@login_required
def delete_link(request, pk):
    link = get_object_or_404(Link, created_by=request.user, pk=pk)  
    link.delete()

    return redirect('/links/')

    

@login_required   
def create_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            category = form.save(commit=False)
            category.created_by=request.user
            category.save()

            return redirect('/dashboard/')
    else:
        form = CategoryForm()

    return render(request, 'link/create_category.html', {
        'form': form,
        'title': 'Create category',
    })

@login_required
def edit_category(request, pk):
    category = get_object_or_404(Category, created_by=request.user, pk=pk)

    if request.method == "POST":
        form=CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()

            return redirect('/links/categories/')
    else:
        form = CategoryForm(instance=category)
    
    return render(request, 'link/create_category.html', {
        'form': form,
        'title': 'Edit category',
    })

@login_required
def delete_category(request, pk):
    category = get_object_or_404(Category, created_by=request.user, pk=pk)  
    category.delete()

    return redirect('/links/categories')

link/templates/link/categories.html
{% extends 'core/base.html' %}

{% block title %} Categories {% endblock %} 

{% block content %} 
    <h1 class="mb-6 text-xl">Categories</h1>

    <a href="{% url 'links:create_category' %}" class="inline-block mb-6 py-4 px-6 bg-cyan-600 text-white rounded-xl">Create category</a>

    <div class="grid grid-cols-3 gap-3">
        {% for category in categories %}
            <div class="bg-gray-100 p-6 rounded-xl">
                <h2 class="mb-4 text-xl">{{ category.name }}</h2>

                <a href="{% url 'links:links' %}?category={{category.id}}" class="text-cyan-700">View</a>
                |
                <a href="{% url 'links:edit_category' category.id %}" class="text-cyan-700">Edit</a>
                |
                <a href="{% url 'links:delete_category' category.id %}" class="text-rose-700">Delete</a>
            </div>
        {% endfor %}
    </div>
{% endblock %} 

link/templates/link/create_category.html
{% extends 'core/base.html' %}

{% block title %} {{title}} {% endblock %} 

{% block content%} 
<h1 class="text-xl">{{title}}</h1>

<form method="post" action=".">
{% csrf_token %}

{{ form.as_p }}

<button class="mt-4 py-4 px-6 bg-cyan-500 text-white rounded-xl">Submit</button>
</form>
{% endblock %} 

link/templates/link/create_link.html
{% extends 'core/base.html' %}

{% block title %} {{title}}{% endblock %} 

{% block content%} 
    <h1 class="text-xl">{{title}}</h1>

    {% if request.user.links.all.count >= request.user.Plan.max_num_links %}
    <div class="p-6 bg-rose-600 mt-6 text-white rounded-xl">
        You have the reached the top of your plan!
    </div>
    {% else %}
        <form method="post" action=".">
            {% csrf_token %}

            {{ form.as_p }}

                <button class="mt-4 py-4 px-6 bg-cyan-500 text-white rounded-xl">Submit</button>
            </form>
    {% endif %}
{% endblock %} 

link/templates/link/links.html
{% extends 'core/base.html' %}

{% block title %} Links {% endblock %} 

{% block content %} 
    <h1 class="text-xl">Links</h1>

    <div class="mb-6 space-x-4 space-y-4">
        {% for category in request.user.categories.all %}
            <a href="{% url 'links:links' %}?category={{category.id}}">{{category.name}}</a>
        {% endfor %}
    </div>

    <div class="grid grid-cols-3 gap-3">
        {% for link in link %}
            <div class="bg-gray-100 p-6 rounded-xl">
                <h2 class="mb-4 text-xl">{{ link.name }}</h2>
                
                {% if link.description %}
                    <p class="mb-4 text-xs">{{ link.description }}</p>
                {% endif %}

                <a href="{{ link.url }}" class="text-cyan-700" target="_blank">Open</a>
                |
                <a href="{% url 'links:edit_link' link.id %}" class="text-cyan-700">Edit</a>
                |
                <a href="{% url 'links:delete_link' link.id %}" class="text-rose-700">Delete</a>
            </div>
        {% empty %}
            <div class="bg-rose-200 p-6 rounded-xl">You don't have any link for this filter..</div>
        {% endfor %}
    </div>
{% endblock %} 