accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views
from .forms import LoginForm

app_name = 'accounts'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('signup/', views.singup, name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login.html',form_class=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("create-sub/", views.create_sub, name="create sub"), 
    path("complete/", views.complete, name="complete"), 
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns= [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('pricing/', views.pricing, name='pricing')
]

lynko/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include('core.urls')),
    path('', include('accounts.urls')),
    path('links/', include('link.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
     path("stripe/", include("djstripe.urls", namespace="djstripe")),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import djstripe
from djstripe.models import Customer, Subscription
# Create your models here.

class plan(models.Model):
    name = models.CharField(max_length=255)
    max_num_links = models.IntegerField()


class User(AbstractUser):
    Plan = models.ForeignKey(plan, related_name='users', default=1, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, null=True, blank=True, on_delete=models.SET_NULL)
    subscription = models.ForeignKey(Subscription, null=True, blank=True,on_delete=models.SET_NULL)
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User
class SignupForm(UserCreationForm): 
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login

from django.conf import settings

import stripe
import djstripe
import json
from django.http import JsonResponse, HttpResponse
from djstripe.models import Product
from django.contrib.auth.decorators import login_required


from .forms import SignupForm, LoginForm



# Create your views here.
def singup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            user = form.save()
            authenticate(username=user.username, password=user.password)

            if user is not None:
                login(request, user)


                return redirect('/dashboard/')

    else:
        form = SignupForm()

    
    return render(request, 'accounts/singup.html',{
        'form': form 
        })


@login_required
def checkout(request):
  products = Product.objects.all()
  return render(request,"accounts/checkout.html",{"products": products})

@login_required
def create_sub(request):
  if request.method == 'POST':
      # Reads application/json and returns a response
      data = json.loads(request.body)
      payment_method = data['payment_method']
      stripe.api_key =settings.STRIPE_TEST_SECRET_KEY

      payment_method_obj = stripe.PaymentMethod.retrieve(payment_method)
      djstripe.models.PaymentMethod.sync_from_stripe_data(payment_method_obj)


      try:
          # This creates a new Customer and attaches the PaymentMethod in one API call.
          customer = stripe.Customer.create(
              payment_method=payment_method,
              email=request.user.email,
              invoice_settings={
                  'default_payment_method': payment_method
              }
          )

          djstripe_customer = djstripe.models.Customer.sync_from_stripe_data(customer)
          request.user.customer = djstripe_customer
         

          # At this point, associate the ID of the Customer object with your
          # own internal representation of a customer, if you have one.
          # print(customer)

          # Subscribe the user to the subscription created
          subscription = stripe.Subscription.create(
              customer=customer.id,
              items=[
                  {
                      "price": data["price_id"],
                  },
              ],
              expand=["latest_invoice.payment_intent"]
          )

          djstripe_subscription = djstripe.models.Subscription.sync_from_stripe_data(subscription)

          request.user.subscription = djstripe_subscription
          request.user.save()

          return JsonResponse(subscription)
      except Exception as e:
          return JsonResponse({'error': (e.args[0])}, status =403)
  else:
    return HttpResponse('requet method not allowed')
  
def complete(request):
    return render(request, "accounts/complete.html")

accounts/templates/accounts/checkout.html
{% extends "core/base.html" %}

{% block content %}
<script src="https://js.stripe.com/v3/"></script>

<br><br>

  
<div class="container ">

  <div class="row ">
    {% for p in products %}
    <div class="col-6">
      <div class="card mx-5 shadow" style="border-radius: 10px; border:none; ">
        <div class="card-body">
          <h5 class="card-title font-weight-bold">{{p.name}}</h5>
          <p class="card-text text-muted"><svg class="bi bi-check" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.236.236 0 0 1 .02-.022z"/>
          </svg>{{p.description}}</p>

          {% for plan in p.plan_set.all %}
          <h5 >{{ plan.human_readable_price }}</h5>
          <div class="text-right">
            <input type="checkbox" name="{{p.name}}" value="{{p.id}}" onclick="planSelect('{{p.name}}' ,'{{plan.human_readable_price}}', '{{plan.id}}')">
          {% endfor %}
          </div>
        </div>
      </div>

    </div>

    {% endfor %}
  </div>
  <br><br><hr><br><br>
  <div>
    <div class="row">
      <div class="col-12">
        <div class="card mx-5 shadow rounded" style="border-radius:50px;border:none">
          <div class="card-body">
            <h5 class="card-title font-weight-bold">Checkout</h5>
            <p class="text-muted ">Enter card details.  Your subscription will start immediately</p>
            <div class="row">
              <div class="col-6 text-muted">
                <p>Plan:</p>
                <p>Total:</p>
              </div>
              <div class="col-6 text-right">
                <p id="plan"></p>
                <p id="price"></p>
                <p hidden id="priceId"></p>
              </div>

            </div>
            <br>
            <form id="subscription-form" >
              <div id="card-element" class="MyCardElement">
                <!-- Elements will create input elements here -->
              </div>
              
              <!-- We'll put the error messages in this element -->
              <div id="card-errors" role="alert"></div>
              <button id="submit" type="submit">
                <div class="spinner-border  spinner-border-sm text-light hidden" id="spinner" role="status">
                  <span class="sr-only">Loading...</span>
                </div>
                <span id="button-text">Subscribe</span>
              </button>
            </form>
          </div>
        </div>

      </div>
    </div>
  </div>

</div>

{% endblock %}

accounts/templates/accounts/complete.html
{% extends "core/base.html" %}

{% block content %}


<div class="container text-center">
<br><br><br><br>
<h3>Your subscription is now active!</h3>
<br><br>
<a class="btn btn-primary text-light" href="/">Return Home</a>
<br><br>
<a class="btn btn-danger text-light" href="/cancel">Cancel Subscription</a>
</div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'core/base.html' %}

{% block title %} Log in {% endblock %} 

{% block content%} 
<h1 class="text-xl">Log in</h1>

<form method="post" action=".">
{% csrf_token %}

{{ form.as_p }}

<button class="mt-4 py-4 px-6 bg-cyan-500 text-white rounded-xl">Submit</button>
</form>
{% endblock %} 

accounts/templates/accounts/singup.html
{% extends 'core/base.html' %}

{% block title %} Sign up {% endblock %} 

{% block content%} 
<h1 class="text-xl">Sign up</h1>

<form method="post" action=".">
{% csrf_token %}

{{ form.as_p }}

<button class="mt-4 py-4 px-6 bg-cyan-500 text-white rounded-xl">Submit</button>
</form>
{% endblock %} 